[package]
name = "iota_oracle_system_state"
version = "0.0.1"
edition = "2024.beta"
published-at = "0x0"
# license = "SPDX-License-Identifier: AGPLv3"
# authors = [""]

[dependencies]


[addresses]
iota_oracle_system_state = "0x0"
