[package]
name = "iota_oracle_system_state"
version = "0.0.1"
edition = "2024.beta"
published-at = "0xb3d876d6abfece04ee4c435a9a7275d830b0a5a09cd96df2d61b09f1892bf48c"
# license = "SPDX-License-Identifier: AGPLv3"
# authors = [""]

[dependencies]
iota_oracle_validator_caps = { local = "../oracle_validator_caps_testnet" }

[addresses]
iota_oracle_system_state = "0xb3d876d6abfece04ee4c435a9a7275d830b0a5a09cd96df2d61b09f1892bf48c"
