[package]
name = "iota_oracle_tasks"
version = "0.0.1"
edition = "2024.beta"
published-at = "0x0"

[dependencies]
iota_oracle_system_state = { local = "../oracle_system_state" }

[addresses]
iota_oracle_tasks = "0x0"
iota_oracle_system_state = "0xf0ce329c6f779d060208e35ab49fe9edea2c4dd263d630f7c47486d685f725ae"
