[package]
name = "iota_oracle_tasks"
version = "0.0.1"
edition = "2024.beta"
published-at = "0xff5ef1d440aa76aee284b90e1e8e7463f3e0388fdd27a2353c82c668250cebee"

[dependencies]
iota_oracle_system_state = { local = "../oracle_system_state_devnet" }

[addresses]
iota_oracle_tasks = "0xff5ef1d440aa76aee284b90e1e8e7463f3e0388fdd27a2353c82c668250cebee"
