[package]
name = "iota_oracle_tasks"
version = "0.0.1"
edition = "2024.beta"
published-at = "0x94bc3f11dfebda058d1b5a0182e3701f6aca1716497806c4ef4f436e4fd3f473"

[dependencies]
iota_oracle_system_state = { local = "../oracle_system_state_devnet" }

[addresses]
iota_oracle_tasks = "0x94bc3f11dfebda058d1b5a0182e3701f6aca1716497806c4ef4f436e4fd3f473"
