[package]
name = "iota_oracle_scheduler"
version = "0.0.1"
edition = "2024.beta"
published-at = "0x0"

[dependencies]
iota_oracle_tasks = { local = "../oracle_tasks_testnet" }

[addresses]
iota_oracle_scheduler = "0x0"
