[package]
name = "iota_oracle_system_state"
version = "0.0.1"
edition = "2024.beta"
published-at = "0x5402bfe6c6fdac542cbe941047504becc1d42a0f4988f80ca3c71f933dc9ef48"
# license = "SPDX-License-Identifier: AGPLv3"
# authors = [""]

[addresses]
iota_oracle_system_state = "0x5402bfe6c6fdac542cbe941047504becc1d42a0f4988f80ca3c71f933dc9ef48"
